@@grammar::FBX_BINARY

start
    =
    fbx_header int_32 fbx_root_node
    ;

fbx_header
    =
    'Kaydara FBX Binary'
    ;

fbx_root_node
    =
    name_len:int_8 version:int_32 offset:int_32 depth:int_32 children:int_32 fbx_node
    ;

fbx_node
    =
    | name_len:int_8 {name:char}* offset:int_32 depth:int_32 children:int_32
    | name_len:int_8 {name:char}* type:data_type {data:byte}+ offset:int_32 depth:int_32 children:int_32
    ;

data_type
    =
    type:/[\x59\x43\x49\x46\x44\x4c\x66\x64\x6c\x69\x62\x53\x52]/
    ;

int_64
    =
    value:(byte byte byte byte byte byte byte byte)
    ;

int_32
    =
    value:(byte byte byte byte)
    ;

int_8
    =
    value:byte
    ;

char
    =
    value:byte
    ;

byte
    =
    value:/./
    ;